# Generated by Django 2.2.6 on 2020-02-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Codigo', models.CharField(db_column='Codigo', max_length=30, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=30)),
                ('Descripcion', models.CharField(db_column='Descipcion', max_length=30)),
                ('Codigo_QR', models.CharField(db_column='Codigo_QR', max_length=30)),
                ('Precio_de_venta', models.IntegerField(db_column='Precio_de_venta')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
