# Generated by Django 2.2.6 on 2020-08-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_multimedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='multimedia',
        ),
    ]
